### ISSUE TITLE
command 'play

### ISSUE THREAD

**Issue by Swiggity11** [martmists/datbot-public#1]
These past few minutes I've been experiencing troubles with the music command, I can't seem to make the join the voice channel, even though it shows the message saying "Now playing: ....."

**Comment by Felilx** [comment]
Same

**Comment by Felilx** [comment]
This has been occurring in multiple servers.

**Comment by martmists** [comment]
As this is a common issue I will investigate it. For now I am working on
server-specific settings and after that I'll see if the same occurs to me.
A known issue right now is that the bot is unable to be called to a channel
after 'stop has been used (unless restarted). ETA for fix: hopefully before
Jan 7

**Comment by martmists** [comment]
Closing as this doesn't seem to occur anymore. If it does feel free to re-open
